# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base/serv_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 330, 631, 103))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.textViewTerminal = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textViewTerminal.setObjectName("textViewTerminal")
        self.verticalLayout.addWidget(self.textViewTerminal)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(360, 0, 271, 331))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.lineEditAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditAddress.setGeometry(QtCore.QRect(90, 40, 113, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditAddress.setFont(font)
        self.lineEditAddress.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditAddress.setAutoFillBackground(False)
        self.lineEditAddress.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditAddress.setObjectName("lineEditAddress")
        self.labelAddress = QtWidgets.QLabel(self.centralwidget)
        self.labelAddress.setGeometry(QtCore.QRect(20, 40, 58, 16))
        self.labelAddress.setObjectName("labelAddress")
        self.labelPort = QtWidgets.QLabel(self.centralwidget)
        self.labelPort.setGeometry(QtCore.QRect(20, 70, 58, 16))
        self.labelPort.setObjectName("labelPort")
        self.lineEditPort = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPort.setGeometry(QtCore.QRect(90, 70, 113, 21))
        self.lineEditPort.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditPort.setObjectName("lineEditPort")
        self.startServBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startServBtn.setGeometry(QtCore.QRect(91, 110, 141, 32))
        self.startServBtn.setObjectName("startServBtn")
        self.btnQuit_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnQuit_2.setGeometry(QtCore.QRect(20, 0, 61, 32))
        self.btnQuit_2.setObjectName("btnQuit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEditAddress.setText(_translate("MainWindow", "127.0.0.1"))
        self.labelAddress.setText(_translate("MainWindow", "Адрес"))
        self.labelPort.setText(_translate("MainWindow", "Порт"))
        self.lineEditPort.setText(_translate("MainWindow", "7777"))
        self.startServBtn.setText(_translate("MainWindow", "Запуск сервера"))
        self.btnQuit_2.setText(_translate("MainWindow", "Quit"))
